# This is a basic workflow to help you get started with Actions

name: git push into another repo to deploy to vercel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: pandoc/latex
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install mustache (to update the dat)
        run: apk add ruby && gem install mustache
      - name: Pushe to another repository
        id: push_directory
        uses: cpina/github-action-push-to-snother-repository@main
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: "output"
          destination-github-username: in-woong
          destination-repository-name: react-shop_TEAM
          user-email: ${{secrets./OFFICIAL_?ACCOUNT_EMAIL}}
          commit-message: ${{github.event.commits[0].message}}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DETINATION_CLONED_DIRECTORY
