name: git push into another repo to deploy to vercel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v2
      - name: create output
        run: sh ./build.sh
      - name: Pushe to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: "output"
          destination-github-username: in-woong
          destination-repository-name: react-shop_TEAM
          user-email: inwoong100@gmail.com
          commit-message: ${{github.event.commits[0].message}}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DETINATION_CLONED_DIRECTORY
